# R for travis documentation: https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: bioc-devel

# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - master

# Test code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  slack:
    secure: YRDHMI2Vk8f6w4AzLTgZ/8lfKbALiEH2kCVZehO3tfY8kstDeanTmy2V9MYLJMe1/K1WVBVHzY6KsDq+H+ZaayWwclviwlFj7ArjZq00ZBsn9eWt2x50u97kZ2cHh+MANfNQuIHScyicrLL2a6FN7CGwARiSFV5wO+fQDNDM9PCQZQqfbzq0NaUpYMbWRBhCkeXtQrK08iZkEPJzrZf4otDZZgQtr87BHj77eA2wYL6pSUuyp2u0AgSq6CYji3pHn5fYW98qkhvcxGuoB0XhqO9UQQv61e/1+TsP4L9wOZYK+Q+G2YoknC9uDj96l+dgPXcF7ImdHD9oKYcBA/USq8L9aQ0fA2ZYsgGWdEmWlqx5ENDl1Vyu8YHbOHpA0IPFY7ba3j5EKclOM+mUAGciz+b1ebHn91dlFfH6E/uwulHAVuiq+UT+WA7CKQgRT/BjLFfPcXf+kG8usxnfXYk4vb+Yzj35wBDa53S7R4ZmSYXzgjT5k7G3yoKShIPRKqnLFGREQEx8O5+/50kebAB5haxiLcpiFGUlunpGA0hJC4I7/K7KtMD/6+U9YAXoX6MYXZJ+FbFPLA/9CctTKQVHvNRbybKlEPHOcwNFEuyRzlyjvS7KHgdIfrXHFA/6kYsCq56mrAjDp9wjQOzDk8cwEzSsRfDuLc6xAaAo+emYj1k=
